# Generated by Django 4.0.1 on 2022-02-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0002_customuser_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='local',
            field=models.CharField(help_text='Your adress!', max_length=255),
        ),
    ]
