# Generated by Django 4.0.1 on 2022-02-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0005_customuser_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(help_text='Имя', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(help_text='Отчество', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(help_text='Фамилия', max_length=100, null=True),
        ),
    ]
