# Generated by Django 4.0.1 on 2022-01-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='film',
            name='description',
        ),
    ]
