# Generated by Django 4.0.1 on 2022-01-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_create_date_remove_book_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raiting', models.IntegerField(choices=[(1, 'Bad'), (2, 'Okey'), (3, 'Fine'), (4, 'Good'), (5, 'Amaizing')])),
                ('rait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
