# Generated by Django 4.0.1 on 2022-01-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='raiting',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Okey'), (3, 'Fine'), (4, 'Good'), (5, 'Amaizing')]),
        ),
    ]
