# Generated by Django 4.0.1 on 2022-01-22 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_raiting_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='rait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raiting_book', to='book.book'),
        ),
    ]
