# Generated by Django 4.0.1 on 2022-01-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_bookcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcomment',
            old_name='comment',
            new_name='book_selection',
        ),
    ]
