# Generated by Django 4.0.1 on 2022-01-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rename_comment_bookcomment_book_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomment',
            name='date_now',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
