# Generated by Django 4.0.1 on 2022-01-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_bookcomment_date_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hobby', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpertBookRecomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('book_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_selection', to='book.book')),
                ('expert_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert', to='book.expertbook')),
            ],
        ),
    ]
