# Generated by Django 4.0.1 on 2022-01-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_expertbook_expertbookrecomendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertbook',
            name='patronymic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expertbook',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
