# Generated by Django 4.0.1 on 2022-01-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_expertbook_patronymic_expertbook_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertbook',
            name='surname',
        ),
    ]
