# Generated by Django 4.0.1 on 2022-01-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_expertbook_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertbookrecomendation',
            name='expert_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.expertbook'),
        ),
    ]
